
version: 2

jobs:
  build:
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - checkout
      - run: go mod download
      - run: gotestsum -ftestname -- ./...
